name: "CI"
on: [push]

jobs:
  check_pr:
    strategy:
      matrix:
        node: [10.x, 12.x]
        os: [ubuntu-18.04, ubuntu-16.04]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v1
      - name: Setup node version
        uses: actions/setup-node@master
        with:
          version: ${{ matrix.node }}

      - name: "npm run lint:fix"
        run: npm run lint:fix
